services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"   # or "false" if you only want manual invites
    volumes:
      - ./vw-data:/data
    ports:
      - "8085:80"
      - "3012:3012"   # <-- websocket port


